server:
  jwt-secret: MTAxNTkwMTg1Mw==
  version: "1.0"
  name: tiktok

snowflake:
  worker-id: 0
  datancenter-id: 0

mysql:
  addr: 127.0.0.1:3306
  database: tiktok
  username: tiktok
  password: tiktok
  charset: utf8mb4

etcd:
  addr: 127.0.0.1:2379

rabbitmq:
  addr: 127.0.0.1:5672
  username: tiktok
  password: tiktok

redis:
  addr: 127.0.0.1:6379
  password: tiktok

services:
  api:
    name: api
    load-balance: false
    addr:
      - 127.0.0.1:10001
  user:
    name: user
    load-balance: false
    addr:
      - 127.0.0.1:10002
  chat:
    name: chat
    load-balance: false
    addr:
      - 127.0.0.1:10003
  follow:
    name: follow
    load-balance: false
    addr:
      - 127.0.0.1:10004
  interactive:
    name: interactive
    load-balance: false
    addr:
      - 127.0.0.1:10005
  video:
    name: video
    load-balance: false
    addr:
      - 127.0.0.1:10006
  experimental:
    name: experimental
    load-balance: false
    addr:
      - 127.0.0.1:10007
      - 127.0.0.1:10008
      - 127.0.0.1:10009
      - 127.0.0.1:10010